### ISSUE TITLE
Build a readme

### ISSUE THREAD

**Issue by posix4e** [reem/transfer#6]
It would be nice to lay out the purpose of the project. I have to admit I am not sure. I was thinking of it as a netty for rust. But perhaps I'm not thinking about it correctly

**Comment by reem** [comment]
The immediate goal is to be a fast HTTP server, with subsystems extractable into standalone, more generic dependencies over time. `netty` is an amazing project, but I personally think we are better suited with more small orthogonal pieces than a monolithic framework.

I haven't yet written a README in part because I'm not yet entirely sure what the scope of the project is, and I don't want to falsely advertise :)

**Comment by posix4e** [comment]
How much do we think it should be http focused? I also wonder if capnproto integration makes sense

**Comment by reem** [comment]
A bit of background: I recently tried to write a full high-level asynchronous io library directly, but it devolved into a big ball of mud in part because it is still unclear what the requirements of a generic async io library and/or eventing framework in rust are. Part of the goal of this project is to write a non-trivial, concrete project based on async io in rust, to see what APIs are important for more generic components to replace what will be hard coded in the initial versions of transfer.

**Comment by posix4e** [comment]
Totally makes sense

**Comment by reem** [comment]
@posix4e In light of the above comment, capnproto integration would probably be built atop the generic pieces after they have been extracted from transfer and generalized.

To sort of get a feel for the way I'd like this to turn out in the end, you can see the internals of iron: lots of small very general packages with a clear separation of concerns, e.g. `modifier`, `plugin`, `typemap`, etc.

EDIT: I do expect the infrastructure for this project to be quite a bit more complex than iron's internals, just because we are dealing with much lower level components at the start.

**Comment by posix4e** [comment]
*nod
